//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRZ_rec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string firstname { get; set; }
        public string lastname { get; set; }
        public byte[] idphoto { get; set; }
    }
}
